baseURL = "https://hereisthedill.com/"
languageCode = "en-us"
title = "Here's the Dill"
theme = "dill"

[[menu.main]]
	name = "Home"
	weight = 100
	identifier = "home"
	url = "/"
[[menu.main]]
	name = "Posts"
	weight = 120
	identifier = "posts"
	url = "/posts"
[[menu.main]]
	name = "Articles"
	weight = 130
	identifier = "articles"
	url = "/articles"
[[menu.main]]
	name = "About"
	weight = 110
	identifier = "about"
	url = "/about"
[[menu.main]]
	name = "Categories"
	weight = 140
	identifier = "categories"
	url = "/categories"
[[menu.main]]
	name = "Glossary"
	weight = 150
	identifier = "glossary"
	url = "/glossary"
[[menu.main]]
	name = "Contact"
	weight = 160
	identifier = "contact"
	url = "/contact"

[[menu.social]]
	name = "Twitter"
	target = "_blank"
	weight = 100
	identifier = "twitter"
	url = "https://twitter.com/hereisthedill"
	pre = "<svg class='feather'><use xlink:href='/img/feather-sprite.svg#twitter'/></svg>"
[[menu.social]]
	name = "Instagram"
	target = "_blank"
	weight = 110
	identifier = "instagram"
	url = "https://instagram.com/hereisthedill"
	pre = "<svg class='feather'><use xlink:href='/img/feather-sprite.svg#instagram'/></svg>"

[params]
    description = "Jayme's German Gardening Journey"
		footer = "Here's the Dill &copy; 2019 Jayme Weglarski | All rights reserved"
